### ISSUE TITLE
Stuck in operation

### ISSUE THREAD

**Issue by Zachary-Zuo** [jan-van-bergen/GPU-Pathtracer#12]
Your project is excellent. But when I try to run it, I get stuck on line 984 in Pathtracer.cpp( global_buffer_sizes.set_value(*buffer_sizes); ). Do you know what happened and how to solve it? Thank you.

**Comment by jan-van-bergen** [comment]
That line is the part where the CPU is forced to sychronize with the CUDA code so it is likely that the CUDA code gets stuck in a loop somewhere.
I had an issue like that before due to area based light sampling; try switching `LIGHT_SELECTION` to `LIGHT_SELECT_UNIFORM` instead of `LIGHT_SELECT_AREA`.

**Comment by 6217Steve99** [comment]
Thank you for your answer, but it still does not work after modification.
