### ISSUE TITLE
[Question] Samples

### ISSUE THREAD

**Issue by knightcrawler25** [jan-van-bergen/GPU-Pathtracer#29]
Hey :)

I've been working on a small hobby path tracer in my spare time (https://github.com/knightcrawler25/GLSL-PathTracer) but reached a point where path tracing in a pixel shader doesn't suffice anymore when it comes to performance and large scenes lol. Came across your project some time ago but re-visiting it now, I see tons of features and its bloody fast too even on my old Maxwell card. Very impressive! The clean code in your repo looks like a really good source for me to learn. So, wanted to thank you for sharing this :) Would it also be possible for you to share sample scenes from the readme (some of the more complex ones with participating media etc which do not have a Mitsuba scene file available) to play around with as it would be easy to gauge performance that way and also since it's rather difficult to convert them from the original. 

Thanks again,
Asif

**Comment by jan-van-bergen** [comment]
Hey, thanks for your comment.
I've seen your project before as well, very cool stuff.

I've put some scenes in a [separate repo](https://github.com/jan-van-bergen/Mitsuba-Scenes), probably should have done that before.
There may be some slight differences between what is seen in the screenshots since sometimes I tweek stuff in the editor before taking a screenshot.

**Comment by knightcrawler25** [comment]
This helps. Thanks a lot :)
